language: python

python:
  - "2.7"

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
  - sudo echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" | tee -a /etc/apt/sources.list.d/10gen.list
  - sudo apt-get -y update -qq
  - sudo apt-get -y install -qq mongodb-10gen

install: "pip install -r requirements/requirements.pip"

script: coverage run --rcfile="./.coveragerc" corpus_browser/manage.py test

after_success:
    coveralls