language: python

python:
  - "2.7"

before_install:
  - sudo su -c "requirements/mongo.sh"

install: "pip install -r requirements/requirements.pip"

script: coverage run --rcfile="./.coveragerc" corpus_browser/manage.py test

after_success:
    coveralls