language: python
python:
  - "2.7"
# command to install dependencies
install: "./requirements/mongo.sh; pip install -r requirements/requirements.pip"
# command to run tests
script: coverage run --rcfile="./.coveragerc" corpus_browser/manage.py test

after_success:
    coveralls